# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: NroNNDhiKVKdTAMBIBe4DIeYsMuej3OQ
            client-secret: hgLROSNnG3Gsy_ABcZ9Je03mGH_wtawPYYCnGtSvrLnBVomg88sQDUlcWgpoGa3X
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-biabz9we.us.auth0.com/